### ISSUE TITLE
"countUp" enhancement suggestion

### ISSUE THREAD

**Issue by D-LUSiON** [VincentLoy/simplyCountdown.js#10]
A little enhancement suggestion - some users might need the script to count up from a past date. Add a parameter "countUp" (default: false) and in "refresh" function, after the seconds are calculated:

if (parameters.countUp && secondsLeft <= 0 )
    secondsLeft *= -1;

and it'll work like a charm!

**Comment by VincentLoy** [comment]
Hello @D-LUSiON !

Thanks a lot for your suggestion. I'm kind of busy right now so I don't have time to make this changes. But feel free to contribute by making a PR. 

Thanks again :)

**Comment by VincentLoy** [comment]
Greetings @D-LUSiON ! I just added the feature :) Took about one year to get time to add it, but it's here ;)
