### ISSUE TITLE
doesn't even work

### ISSUE THREAD

**Issue by raymondSeger** [VincentLoy/simplyCountdown.js#11]
<div style="font-family: CenturyGothic; color: #79BDB9; font-size: 18px;" class="countdownTimer"></div>

if( $('.countdownTimer').length ) {
         $('.countdownTimer').simplyCountdown({
            year    : 2018,
            month   : 9,
            day     : 21
        });

    }

**Comment by VincentLoy** [comment]
I close this issue because of inactive issue.
