### ISSUE TITLE
Feature: trigger function when days, hours, minutes turn to 0

### ISSUE THREAD

**Issue by bkmorse** [VincentLoy/simplyCountdown.js#14]
Or add the option to remove 0 days, 0 hours, 0 minutes automatically.

so:

0 days 0 hours 22 minutes 30 seconds

would be:

22 minutes 30 seconds

**Comment by VincentLoy** [comment]
It should be a great option, if you want to contribute you're welcome :smiley: 

That may be easly made by adding a new option like `autoRemove: true`. With default to `false`.
I suggest to add a parametric class to the main countdown element like `-autoremove` if set to `true` to easly update the countdown CSS in that case.

Then, most of the work is to implement conditional checks to hide unwanted elements.

**Comment by VincentLoy** [comment]
Fixed by 0bd24f66572209391b9fd6358c404ce148c59a35
