### ISSUE TITLE
It is possible to import/use this with Webpack?

### ISSUE THREAD

**Issue by newalphamedia** [VincentLoy/simplyCountdown.js#18]
Hi. I'm having trouble importing/using this. I am using Laravel / Laravel Mix / Webpack. I've npm installed the javascript but don't know how to actually install it into my site code?

**Comment by arbabi2010** [comment]
Hi. I had this issue to and i delete comment's end of simplyCountdown.min.js file and it's ok right now

**Comment by VincentLoy** [comment]
Greetings @newalphamedia ! did you find a way to use it using webpack ?

**Comment by newalphamedia** [comment]
No, never did manage to. I am using an alternative script that suites my needs presently.

**Comment by VincentLoy** [comment]
> No, never did manage to. I am using an alternative script that suites my needs presently.

Thanks for your reply. This plugin is quite old now, should be great to make an update :)
