### ISSUE TITLE
Feature: Plurals mapping for languages that doesn't have plurals with a single character 

### ISSUE THREAD

**Issue by tragamota** [VincentLoy/simplyCountdown.js#23]
For example the dutch language: 

Singular:

- Dag
- Uur
- Minuut
- Seconde

Plurals:

- Dagen
- Uren
- Minuten
- Seconden

This is not fixed by a simple by a single 's'

**Comment by VincentLoy** [comment]
Hello @tragamota ! Oh, that's interesting. Did you have an idea to get it working easly ?

**Comment by VincentLoy** [comment]
Hi @tragamota ! Fixed in #15
