### ISSUE TITLE
UTC Support

### ISSUE THREAD

**Issue by christiemerrill** [VincentLoy/simplyCountdown.js#4]
My countdowns are ending too early in other time zones. It would be nice to be able to set a UTC time to make sure everyone seeing it is seeing the same thing.

**Comment by VincentLoy** [comment]
Hi @christiemerrill  ! Thanks to report this issue.
Fixed in v1.2.0 here https://github.com/VincentLoy/simplyCountdown.js/releases/tag/v1.2.0

You can install it via npm too.

:cactus:
