### ISSUE TITLE
How to set the target date?

### ISSUE THREAD

**Issue by fulopd52** [VincentLoy/simplyCountdown.js#40]
What am I doing wrong? I change the date here, but the counter shows 67 seven days instead of 190. (Today is the 7th of January, 2022)

simplyCountdown = function (elt, args) {
        var parameters = extend({
                year: 2022,
                month: 7,
                day: 16,
                hours: 16,
                minutes: 0,
                seconds: 0,
                words: {
                    days: 'day',
                    hours: 'hour',
                    minutes: 'minute',
                    seconds: 'second',
                    pluralLetter: 's'
                },
                plural: false,
                inline: false,
                enableUtc: false,
                
Thank you!

**Comment by VincentLoy** [comment]
simplyCountdown was done to be used as a Javascript library, you don't have to update the core code to get it working.
You should follow the getting started here : https://github.com/VincentLoy/simplyCountdown.js#getting-started
