### ISSUE TITLE
0 uses singular word instead of plural word

### ISSUE THREAD

**Issue by orangerkater** [VincentLoy/simplyCountdown.js#42]
When the value hits `0`, the plural word should be used instead of the singular word.

Currently it shows `0 day` instead of `0 days`. See also https://ell.stackexchange.com/a/51183.

**Comment by VincentLoy** [comment]
Interesting.
Should be optional by a parameter, because if I take French as an example, [both solutions are valid](https://dictionnaire.lerobert.com/guide/accord-du-nom-apres-zero).
