### ISSUE TITLE
Remove unnessary units

### ISSUE THREAD

**Issue by gototog** [VincentLoy/simplyCountdown.js#46]
Is there any way to remove days when no days are needed?
Expected behavior:
`2 days, 1 hour, 10 minutes, 0 second => 2 days,1 hour,10 minutes, 0 seconds `
`0 day, 1 hour, 10 minutes, 0 second => 1 hour,10 minutes, 0 seconds `
`0 day, 0 hour, 10 minutes, 0 second => 10 minutes, 0 seconds `
`0 day, 0 hour, 0 minute, 03 seconds =>  03 seconds `

![image](https://user-images.githubusercontent.com/4048378/176466158-c67b7494-01e4-4939-bf55-839fdb2c99a7.png)

**Comment by VincentLoy** [comment]
This could be added as a new feature with a new parameter :)

**Comment by VincentLoy** [comment]
Related to #14 and fixed by 0bd24f66572209391b9fd6358c404ce148c59a35
