### ISSUE TITLE
Missing configuration detail in UMD instructions?

### ISSUE THREAD

**Issue by cjkpl** [VincentLoy/simplyCountdown.js#54]
First of all - amazing work, thank you for making it available!

It seems to me that when the library is used in UMD mode, user needs to add a respective div with id and class, e.g.
```
<div class="simply-countdown-circle" id="mycountdown"></div>
```
Where class name must match selected theme.
I couldn't make it work any other way - so either I am doing something wrong, or requirement to add  is not explicitly mentioned in the readme?

**Comment by VincentLoy** [comment]
Hi @cjkpl,

Thank you for your kind words and for bringing this to my attention. You're absolutely right; the current documentation lacks explicit instructions regarding the necessity of adding a `<div>` (or any HTML element where you want your countdown to display in fact) and the CSS classes used for each built-in themes. (in fact, both UMD and ES mode are working the same way). 

Each built-in themes have its own unique CSS class so users can set different countdowns in the same page using different themes.

if you are using the UMD mode in the most classic way, you should do something like : 

```html
<div class="any-class simply-countdown-circle"></div>
    
<script src="the/path/to/simplyCountdown.umd.js"></script>
<script>
    simplyCountdown('.any-class', { /* your options */ });
</script>
```

You can use `simplyCountdown` to target any CSS selector (class, id, attributes, etc) as it will basically do a `document.querySelectorAll('YOUR SELECTOR')` to target it.

As the sole developer of this library, I sometimes overlook details that seem obvious to me but may not be clear to new users. I will update the documentation to include these details, ensuring that future users have a clearer understanding of the implementation requirements.

If you have any further questions or need additional assistance, please don't hesitate to ask.
