### ISSUE TITLE
Just showing a few hours as countdown returns 0 0 0 0

### ISSUE THREAD

**Issue by pliebig** [VincentLoy/simplyCountdown.js#8]
If you specify the same year, to get a countdown for just a few hours like
![screen shot 2016-07-28 at 16 37 56](https://cloud.githubusercontent.com/assets/1651645/17216637/c789fe82-54e1-11e6-827f-cbe61e4f8052.png)
you receive:
![screen shot 2016-07-28 at 16 38 08](https://cloud.githubusercontent.com/assets/1651645/17216638/c78a2cb8-54e1-11e6-8e57-358d4cf41363.png)

if i change the year to 2017
![screen shot 2016-07-28 at 16 38 20](https://cloud.githubusercontent.com/assets/1651645/17216669/e206cbc8-54e1-11e6-8ba8-e95dc4ed3414.png)

it works
![screen shot 2016-07-28 at 16 38 24](https://cloud.githubusercontent.com/assets/1651645/17216673/e8fd5eba-54e1-11e6-86a7-036337c6ceaf.png)

**Comment by VincentLoy** [comment]
Hi @pliebig ! This is may be caused because the `hours` parameter takes an Integer between `0` and `23`. So if you want `4pm` you have to put `16`.  Tell me if it worked :)

**Comment by pliebig** [comment]
Hi @VincentLoy  
Thank you very much. You are absolutely right. I wanted to have 4:30 in the morning, but i was totally on the wrong day 😄 

Appreciate your time and the fast response!

Kind Regards

**Comment by VincentLoy** [comment]
Hey @pliebig, happy to hear that you can solved your problem. Thank you for using simplyCountdiwn. :)
