### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by gacor84** [VincentLoy/simplyCountdown.js#9]
Hi!

Is it possible to change the words displayed on the countdown so one could change the language? Thank you!

**Comment by VincentLoy** [comment]
Hello @gacor84 ! You can change the language by editing the `words` parameter that is a Javascript Object.

Taken from the readme example:
```javascript
words: { //words displayed into the countdown
    days: 'day',
    hours: 'hour',
    minutes: 'minute',
    seconds: 'second',
    pluralLetter: 's'
},
```
Hope that'll help :+1:
